name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pr-checks:
    name: PR checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

    - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86  # v6.0.10

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f  # v6.3.0
      with:
        node-version: '22.x'
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
    - run: pnpm check:issue-template
    - run: pnpm turbo type-check
    - run: pnpm turbo lint
    - run: pnpm turbo build
    - run: pnpm turbo test
