name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Node.js dependencies
      run: npm ci

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lasio pandas numpy

    - name: Lint JavaScript/TypeScript
      run: npm run lint

    - name: Test tools
      run: |
        # Test TypeScript tools
        npx tsx .claude-flow/tools/las-parse.ts data/samples/demo.las --json
        npx tsx .claude-flow/tools/web-fetch.ts https://httpbin.org/json
        
        # Test Python tools
        python .claude-flow/tools/curve-qc.py data/samples/demo.las CURVE=GR

    - name: Verify branding compliance
      run: |
        export RUN_ID=ci-test-$(date +%Y%m%d-%H%M%S)
        mkdir -p data/outputs/$RUN_ID
        echo "Generated with SHALE YEAH (c) Ryan McDonald / Ascendvent LLC - Apache-2.0" > data/outputs/$RUN_ID/test.md
        bash scripts/verify-branding.sh

    - name: Test agent generation
      run: npm run gen

    - name: Check for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  security:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript, python

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3