name: Secret Detection

on:
  push:
    branches: [ main, develop, create_project ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    name: Detect secrets with Gitleaks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v5
      if: failure()
      with:
        name: gitleaks-report-${{ github.run_number }}-${{ github.sha }}
        path: gitleaks-report.json

  verify-no-secrets:
    runs-on: ubuntu-latest
    name: Verify no secrets in demo data
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check demo files for secrets
      run: |
        echo "Checking demo data files for accidental secrets..."
        
        # Check for common secret patterns in demo files
        if grep -r -i "password\|secret\|token\|key" data/samples/ --exclude="*.txt" || true; then
          echo "⚠️  Found potential secret patterns - verifying they are demo data..."
        fi
        
        # Verify demo files are clearly marked as demo/test data
        if ! grep -q -i "demo\|test\|sample" data/samples/demo.las; then
          echo "❌ Demo LAS file missing demo identifier"
          exit 1
        fi
        
        echo "✅ Demo data verified clean"

    - name: Verify environment variable usage
      run: |
        echo "Checking for hardcoded credentials in code..."
        
        # Check TypeScript/JavaScript files for hardcoded secrets
        if find src/ tools/ scripts/ -name "*.ts" -o -name "*.js" | xargs grep -l -E "(api_key|token|secret|password)\s*=\s*['\"][^'\"]{8,}" 2>/dev/null || true; then
          echo "⚠️  Found potential hardcoded credentials - manual review needed"
        fi
        
        # Check for environment variable usage patterns (should be process.env.XXX)
        if find src/ -name "*.ts" | xargs grep -E "process\.env\.[A-Z_]+" | head -5; then
          echo "✅ Found proper environment variable usage patterns"
        fi
        
        echo "✅ Secret detection completed"